apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value:  {{ .Values.mysql.password }} 
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}" 

          volumeMounts:
            - name: mysql-storage
              mountPath:  "{{ .Values.mysql.mountPath }}"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: "{{ .Values.mysql.name }}-pvc"
